# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Definicje',
            fields=[
                ('iddefinicji', models.AutoField(db_column='idDefinicji', primary_key=True, serialize=False)),
                ('definicja', models.CharField(db_column='Definicja', max_length=45)),
                ('liczbalike', models.IntegerField(db_column='LiczbaLike')),
                ('datadodania_definicji', models.DateField(blank=True, db_column='DataDodania_Definicji', null=True)),
            ],
            options={
                'db_table': 'definicje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kursy',
            fields=[
                ('idkursu', models.AutoField(db_column='idKursu', primary_key=True, serialize=False)),
                ('kurs_name', models.CharField(db_column='Kurs_name', max_length=45)),
            ],
            options={
                'db_table': 'kursy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Likedefinicji',
            fields=[
                ('idlike_def', models.AutoField(db_column='idLike_Def', primary_key=True, serialize=False)),
                ('czylike', models.IntegerField(db_column='CzyLike')),
            ],
            options={
                'db_table': 'likedefinicji',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Likeslowa',
            fields=[
                ('idlike_slowa', models.AutoField(db_column='idLike_Slowa', primary_key=True, serialize=False)),
                ('czylike', models.IntegerField(db_column='CzyLike')),
            ],
            options={
                'db_table': 'likeslowa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('numer_indeksu', models.AutoField(db_column='Numer_indeksu', primary_key=True, serialize=False)),
                ('email_pwr', models.CharField(db_column='Email_pwr', max_length=45)),
                ('imie', models.CharField(db_column='Imie', max_length=45)),
                ('nazwisko', models.CharField(db_column='Nazwisko', max_length=45)),
                ('nickname', models.CharField(db_column='Nickname', max_length=45)),
                ('aktywowane_konto', models.CharField(db_column='Aktywowane_konto', max_length=45)),
                ('haslo', models.CharField(db_column='Haslo', max_length=45)),
            ],
            options={
                'db_table': 'uzytkownicy',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='slowa',
            options={'managed': False},
        ),
    ]
