# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-13 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20180512_1826'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slowa',
            table='slowa',
        ),
    ]
